backend:
  name: github
  repo: sumanshrestha6-sketch/suman-p0rtfolio
  branch: main
  auth_type: oauth
  app_id: Ov23liTBdKdaTqfhW3o7

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - label: "Photography"
        name: "photography"
        file: "content/photography.md"
        fields:
          - label: "Photos"
            name: "photos"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Category", name: "category", widget: "string" }
      - label: "Videos"
        name: "videos"
        file: "content/videos.md"
        fields:
          - label: "Video List"
            name: "videos"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL", name: "url", widget: "string" }
